### ISSUE TITLE
Certificate removed from load balancer when destroying shib service

### ISSUE THREAD

**Issue by dimpsey** [techservicesillinois/terraform-aws-ecs-service#22]
Overview:
While integrating shibboleth with the Course Explorer, it was noticed that the courses.as-test.techservices.illinois.edu certificate was removed from the public2 load balancer upon destroying the shibboleth implementation.

During the destroy process the following destroy action is listed:
- aws_lb_listener_certificate.default

And in the output, the following is logged:
aws_lb_listener_certificate.default: Destruction complete after 0s

Result:
Certificate is no longer attached to public2 load balancer.

Code used to apply and destroy shibboleth for the CIS:
https://github.com/dimpsey/as-aws-test/tree/feature/cis/us-east-2/techservicesastest2-vpc/services/cis/apps/shib

Current work around:
After Certificate is removed, go to console, open up the public2 alb, click on listener, and then re-add the courses.as-test.techservices.illinois.edu certificate.

**Comment by ddriddle** [comment]
@dimpsey This is not a bug. The manual says the following about the `certificate_domain` attribute:

> `certificate_domain` - (Optional) The domain name associated with an Amazon Certificate Manager (ACM) certificate. If specified, the certificate is looked up by the domain name, and the resulting certificate ARN is associated with the listener for the ECS service.
https://github.com/techservicesillinois/terraform-aws-ecs-service/blob/feature/migrate/README.md#load_balancer

The name is not the best, a better name might be `attach_certificate`, but it does what it was designed and documented to do. The remedy is to either associate the `certificate_domain` attribute with a single `terraform.tfvars`, so that you avoid race conditions, or perform the certificate attachment separately using our [lb-listener-certificate](https://github.com/techservicesillinois/terraform-aws-lb-listener-certificate) module.

**Comment by JonRoma** [comment]
So much has changed since this issue was created; not worth further effort.
